In [78]:
import numpy as np
import random
import datetime

In [79]:
def KRR_function(X,y,z):
    return (X-3)**3+(y-1)**3+z**3

In [80]:
def create_hyperparams_grid(X,y,z):
    graph_x = []
    graph_y = []
    graph_z = []
    graph_result=[]
    for alpha_value in X:
        graph_x_row = []
        graph_y_row = []
        graph_z_row = []
        graph_result_row = []
        for gamma_value in y:
            for beta_value in z:
                rmse = KRR_function(alpha_value,gamma_value,beta_value)
                graph_x_row.append(alpha_value)
                graph_y_row.append(gamma_value)
                graph_z_row.append(beta_value)
                graph_result_row.append(rmse)
            graph_x.append(graph_x_row)
            graph_y.append(graph_y_row)
            graph_z.append(graph_z_row)
            graph_result.append(graph_result_row)
    graph_x=np.array(graph_x)
    graph_y=np.array(graph_y)
    graph_z=np.array(graph_z)
    graph_result=np.array(graph_result)
    max_result = np.max(graph_result)
    pos_max_result = np.argwhere(graph_result == np.max(graph_result))[0]
    print('Minimum RMSE: %.4f' %(max_result))
    print('Optimum alpha: %f' %(graph_x[pos_max_result[0],pos_max_result[1]]))
    print('Optimum gamma: %f' %(graph_y[pos_max_result[0],pos_max_result[1]]))
    print('Optimum beta: %f' %(graph_z[pos_max_result[0],pos_max_result[1]]))
    return graph_x,graph_y,graph_z,graph_result

In [81]:
x1=np.arange(-200,200,2)
x2=np.arange(-100,100,2)
x3=np.arange(-100,100,2)

In [86]:
current_time1 = datetime.datetime.now()

In [87]:
create_hyperparams_grid(x1,x2,x3)

Minimum RMSE: 9268740.0000
Optimum alpha: 198.000000
Optimum gamma: 98.000000
Optimum beta: 98.000000


(array([[-200, -200, -200, ..., -200, -200, -200],
        [-200, -200, -200, ..., -200, -200, -200],
        [-200, -200, -200, ..., -200, -200, -200],
        ...,
        [ 198,  198,  198, ...,  198,  198,  198],
        [ 198,  198,  198, ...,  198,  198,  198],
        [ 198,  198,  198, ...,  198,  198,  198]]),
 array([[-100, -100, -100, ...,   98,   98,   98],
        [-100, -100, -100, ...,   98,   98,   98],
        [-100, -100, -100, ...,   98,   98,   98],
        ...,
        [-100, -100, -100, ...,   98,   98,   98],
        [-100, -100, -100, ...,   98,   98,   98],
        [-100, -100, -100, ...,   98,   98,   98]]),
 array([[-100,  -98,  -96, ...,   94,   96,   98],
        [-100,  -98,  -96, ...,   94,   96,   98],
        [-100,  -98,  -96, ...,   94,   96,   98],
        ...,
        [-100,  -98,  -96, ...,   94,   96,   98],
        [-100,  -98,  -96, ...,   94,   96,   98],
        [-100,  -98,  -96, ...,   94,   96,   98]]),
 array([[-10395728, -10336920, -10280

In [88]:
current_time2 = datetime.datetime.now()
print (current_time2 - current_time1)

0:01:53.939414


In [77]:
len(x1)

200